// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIReMJ3QR6WIxfiIXZk67nqcQzf0oZV-w',
    appId: '1:675844961310:web:711438bdc673dfc462ea0f',
    messagingSenderId: '675844961310',
    projectId: 'flutter-auth-b2323',
    authDomain: 'flutter-auth-b2323.firebaseapp.com',
    storageBucket: 'flutter-auth-b2323.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGb9iUGLPviGXwhbO-GHZeejCZ_NFz0xo',
    appId: '1:675844961310:android:ae33fa73b6c4330762ea0f',
    messagingSenderId: '675844961310',
    projectId: 'flutter-auth-b2323',
    storageBucket: 'flutter-auth-b2323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyYVG7ib60qx4uyRgmsWsYX4iXfirDzw',
    appId: '1:675844961310:ios:2b9a55fb1b2f06d262ea0f',
    messagingSenderId: '675844961310',
    projectId: 'flutter-auth-b2323',
    storageBucket: 'flutter-auth-b2323.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyYVG7ib60qx4uyRgmsWsYX4iXfirDzw',
    appId: '1:675844961310:ios:2b9a55fb1b2f06d262ea0f',
    messagingSenderId: '675844961310',
    projectId: 'flutter-auth-b2323',
    storageBucket: 'flutter-auth-b2323.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIReMJ3QR6WIxfiIXZk67nqcQzf0oZV-w',
    appId: '1:675844961310:web:5dae8f2e151e8b5262ea0f',
    messagingSenderId: '675844961310',
    projectId: 'flutter-auth-b2323',
    authDomain: 'flutter-auth-b2323.firebaseapp.com',
    storageBucket: 'flutter-auth-b2323.firebasestorage.app',
  );

}